export default [
    '                         ',
    '                      xxx',
    '          o       o   xxx',
    '                      xxx',
    '                      xxx',
    '    p o        x      xxx',
    'xx  xxxx   xxxxx      xxx',
    'xx  xxxx   xxxxx      xxx',
    'xx  xxxx   xxxxx      xxx',
    'xx  xxxx   xxxxx      xxx',
    'xx  xxxx   xxxxx      xxx',
    'xx  xxxx   xxxxx      xxx',
    'xx  xxxx   xxxxx      xxx',
    'xx  xxxxxxxxxxxx      xxx',
    'xx  xxxxxxxxxxxx      xxx',
    'xx  xxxxxxxxxxxx      xxx',
    'xx  xxxxxxxxxxxx      xxx',
    'xxxxxxxxxxxxxxxx      xxx',
]