"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Boot_1 = require("./Boot");
var Preload_1 = require("./Preload");
var MainMenu_1 = require("./MainMenu");
var Stage = new Phaser.Game(800, 600);
Stage.state.add('Boot', Boot_1.default);
Stage.state.add('Preload', Preload_1.default);
Stage.state.add('MainMenu', MainMenu_1.default);
Stage.state.start('Boot');
